# typed: false
# frozen_string_literal: true

# This formula is auto-generated by the release workflow.
# Do not edit manually — changes will be overwritten.

class Budi < Formula
  desc "Local-first cost analytics for AI coding agents"
  homepage "https://github.com/siropkin/budi"
  version "7.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/siropkin/budi/releases/download/v7.1.0/budi-v7.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "fdc6b6efddbb4ba4be3fdf537e258b9fe80ef587142c0f5ebc3211a1dd29ba1f"
    else
      url "https://github.com/siropkin/budi/releases/download/v7.1.0/budi-v7.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "67ab6da83d355db6faa96bea22749547679e2efc0831cd560f53debb64b6314f"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/siropkin/budi/releases/download/v7.1.0/budi-v7.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "4f8a61d799cb72ab72b3eefa52933b73aa082002ddd276dca744b1165ba38c62"
    else
      url "https://github.com/siropkin/budi/releases/download/v7.1.0/budi-v7.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "5a34f437af2c7fb2bcb6b05281564f282636a6875ecfad47c8c4a05cd7eb0793"
    end
  end

  def install
    bin.install "budi"
    bin.install "budi-daemon"
  end

  def caveats
    <<~EOS
      To get started, run:
        budi init
        budi doctor     # verify everything is working

      This starts the daemon, installs hooks, and syncs your data.
      Restart Claude Code and Cursor to activate hooks and the status line.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/budi --version")
  end
end
