# typed: false
# frozen_string_literal: true

# This formula is auto-generated by the release workflow.
# Do not edit manually — changes will be overwritten.

class Budi < Formula
  desc "Local-first cost analytics for AI coding agents"
  homepage "https://github.com/siropkin/budi"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/siropkin/budi/releases/download/v8.5.0/budi-v8.5.0-aarch64-apple-darwin.tar.gz"
      sha256 "78a758bab25d0823905704a8a218dd8a4a18db406e63dbfcdf1a07c3830972b5"
    else
      url "https://github.com/siropkin/budi/releases/download/v8.5.0/budi-v8.5.0-x86_64-apple-darwin.tar.gz"
      sha256 "da28b3b2bf6b0c12e3fead7e54c48d5d24e1eb47f338fbab30c2b699ae44f6ab"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/siropkin/budi/releases/download/v8.5.0/budi-v8.5.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "1916618047ffb2e1f1c4bb2f7ddf914123a289685ee26ee5cfd0476930d17c79"
    else
      url "https://github.com/siropkin/budi/releases/download/v8.5.0/budi-v8.5.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "dacc103708a6e0ab81d63878a41ddad26d3a1ee8fce5c0c9fc83ad0786abe868"
    end
  end

  def install
    bin.install "budi"
    bin.install "budi-daemon"
  end

  def caveats
    <<~EOS
      Get started:
        budi init

      Restart Claude Code and Cursor to activate hooks and the status line.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/budi --version")
  end
end
