# typed: false
# frozen_string_literal: true

# This formula is auto-generated by the release workflow.
# Do not edit manually — changes will be overwritten.

class Budi < Formula
  desc "Local-first cost analytics for AI coding agents"
  homepage "https://github.com/siropkin/budi"
  version "7.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/siropkin/budi/releases/download/v7.3.0/budi-v7.3.0-aarch64-apple-darwin.tar.gz"
      sha256 "6f86b04f59dd5a52731ac012deca2dc04520fe8a77589a9c9d5bf42b427e4e4d"
    else
      url "https://github.com/siropkin/budi/releases/download/v7.3.0/budi-v7.3.0-x86_64-apple-darwin.tar.gz"
      sha256 "e59275802f0a1e1e3b323e34d23115bdac10fbb2c97d2105424546e69fd7433c"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/siropkin/budi/releases/download/v7.3.0/budi-v7.3.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "cec10d124cfafe3db80fd0b687322a9d1f9e3989638f086022878e9c534b3dca"
    else
      url "https://github.com/siropkin/budi/releases/download/v7.3.0/budi-v7.3.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "6b20878d4c103993fbc6caad7fdfdd5251b73afbe82326dcad9476cdb3d08367"
    end
  end

  def install
    bin.install "budi"
    bin.install "budi-daemon"
  end

  def caveats
    <<~EOS
      Get started:
        budi init

      Restart Claude Code and Cursor to activate hooks and the status line.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/budi --version")
  end
end
